name: CI/CD Simulasi Java

on:
  push:
    branches: [ "main" ] 

jobs:
  # Tahap Continuous Integration (CI)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' 
        distribution: 'temurin'

    - name: Build and Analyze with SonarQube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Sheilaa5_Simulasi-CICD-Java -Dsonar.organization=sheilaa5

  # Tahap Continuous Deployment (CD) Simulasi
  deploy:
    needs: build-and-test 
    runs-on: ubuntu-latest
    steps:
    - name: Simulate Deployment
      run: |
        echo "Memulai proses deployment..."
        echo "Deploy aplikasi ke server production berhasil!"
        echo "Simulasi Continuous Deployment Selesai."
